services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: "${CONTAINER_NAME}"
    ports:
      - "${CONTAINER_PORT}:8000"
    volumes:
      - ../:/app
      - ../storage/logs:/app/storage/logs
      - ../bootstrap/cache:/app/bootstrap/cache
    working_dir: /app
    networks:
      - optima
networks:
    optima:
        external: true
